name: bot-actions

on:
  push:
    branches:
      - "14.0"


jobs:
  post-push-actions:
    runs-on: ubuntu-latest
    concurrency: 
      group: new-${{ github.event.ref }}
      cancel-in-progress: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: ocmt
        uses: odoo-it/github-action-ocmt@master
        with:
          repository: github.event.repository.name
          organization: github.event.repository.owner.name
          branch: "14.0"
          gen-addons-table: "true"
          gen-addons-readme: true
          gen-addons-icon: true
          commit: "true"
      -
        name: Push
        run: git push
