name: bot-actions

on:
  push:
    branches:
      - "14.0"


jobs:
  post-push-actions:
    runs-on: ubuntu-latest
    concurrency: 
      group: new-${{ github.event.ref }}
      cancel-in-progress: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: ocmt
        uses: odoo-it/github-action-ocmt@master
        with:
          addons-dir: "."
          repo-name: github.event.repository.name
          org-name: github.event.repository.owner.name
          branch-name: "14.0"
      -
        name: Push
        run: git push
